### ISSUE TITLE
Stretching out image

### ISSUE THREAD

**Issue by Talgat777** [natario1/CameraView#64] opened 2017-10-12 11:16 UTC
Hey,

We are having an issue with Camera view stretching and not showing in full screen for Galaxy tab 4 android version 5.0.2.

On other devices tested so far the view works fine.

See the screenshot

![screen shot 2017-10-12 at 17 13 16](https://user-images.githubusercontent.com/5118302/31493400-e4a82bca-af70-11e7-899a-4c920f2f2e66.png)

**Comment by natario1** [comment] 2017-10-12 11:20
Can you reproduce this inside the demo app? If so, can you post logs from the buggy device?

**Comment by Talgat777** [comment] 2017-10-12 14:56
It doesn't stretch when running demo. What can we do wrong?
  
![image uploaded from ios](https://user-images.githubusercontent.com/5118302/31502727-b678cc90-af8f-11e7-9dde-33b08903f97a.jpg)

**Comment by natario1** [comment] 2017-10-12 15:00
I don't know. Try to put it out of useless containers, avoid messy stuff (overriding `onMeasure` or similar)

**Comment by Talgat777** [comment] 2017-10-12 15:03
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:tools="http://schemas.android.com/tools"
    android:background="@color/overlay"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical">

    <com.otaliastudios.cameraview.CameraView
        android:id="@+id/camera"
        android:keepScreenOn="true"
        app:cameraFacing="back"
        app:cameraJpegQuality="100"
        app:cameraWhiteBalance="auto"
        app:cameraHdr="off"
        app:cameraSessionType="picture"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <ImageView
        android:id="@+id/result"
        android:layout_width="100dp"
        android:layout_height="100dp"
        android:layout_gravity="bottom"
        android:layout_margin="10dp"
        android:scaleType="centerCrop" />

    <ImageButton
        android:id="@+id/ib_library"
        android:layout_width="56dp"
        android:layout_height="56dp"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:layout_margin="10dp"
        android:background="@drawable/background"
        android:src="@drawable/library_button" />

    <ImageButton
        android:id="@+id/ib_take_photo"
        android:layout_width="56dp"
        android:layout_height="56dp"
        android:layout_alignParentBottom="true"
        android:layout_centerHorizontal="true"
        android:layout_margin="10dp"
        android:background="@drawable/background"
        app:srcCompat="@drawable/ic_photo" />

    <TextView
        android:id="@+id/no_permission"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal|bottom"
        android:layout_marginBottom="50dp"
        android:layout_alignParentBottom="true"
        android:layout_centerHorizontal="true"
        android:text="No Camera permission granted."
        android:textSize="20sp"
        android:visibility="gone"
        tools:visibility="visible" />

    <ImageButton
        android:id="@+id/switchCamera"
        android:layout_width="56dp"
        android:layout_height="56dp"
        android:background="@drawable/background"
        app:srcCompat="@drawable/ic_switch"
        android:layout_gravity="top|right"
        android:layout_alignParentTop="true"
        android:layout_alignParentRight="true"
        android:layout_margin="10dp"/>



</RelativeLayout>

**Comment by natario1** [comment] 2017-10-12 15:07
It looks like it won't work well inside RelativeLayouts, see #63 also

**Comment by Talgat777** [comment] 2017-10-12 15:36
Front camera image is upside down though

![image uploaded from ios 1](https://user-images.githubusercontent.com/5118302/31504890-5b4f8b78-af95-11e7-8b75-53ab0c17c4fb.jpg)

**Comment by natario1** [comment] 2017-10-13 13:38
@Talgat777 can you open a new issue with that? And close this one if it is solved.

In the new issue please add steps to reproduce the issue in the demo app, and demo app logs until the moment the issue is visible

**Comment by natario1** [comment] 2017-11-19 11:38
It's been a month now, I'm closing this. Feel free to open a new issue if the problem persist with latest version, and filling the issue form.

**Closed by natario1** 2017-11-19 11:38 UTC
Labels: on hold

**Comment by saidurcse** [comment] 2018-10-01 10:47
I have reproduced the issue in demo app. Please let me know do you need any more information regarding this issue?
