### ISSUE TITLE
Odd even video rotation issue in video capture

### ISSUE THREAD

**Issue by Ashutosh-Tiwari** [natario1/CameraView#75] opened 2017-10-25 13:22 UTC
I am using the library for capturing multiple videos in one (like instagram).
But the issue is that when we flip the camera from real to back the rotation goes wrong.
Example scenario: If we start video capture from rear, and capture a video then flip the camera to front and capture a video and repeat the same for all video clips, the final video will contain all rear video clips with rotation 90 (correct) and all front video clips with rotation of 270 (Up side down - incorrect)
Please make the rotation value to be changed dynamically no matter how many times we capture the video.

**Comment by natario1** [comment] 2017-10-25 14:59
This is a duplicate of #72 .

We don't choose the orientations, the camera manufacturer and the device tilting do. 90 might be correct for your phone but not for all. In the demo app front videos reproduce just fine.

**Closed** 2017-10-26 15:07 UTC
